[package]
name = "secretspec"
version.workspace = true
edition.workspace = true
repository = "https://github.com/cachix/secretspec"
description = "Declarative secrets, every environment, any provider"
license = "Apache-2.0"

[lib]
name = "secretspec"
path = "src/lib.rs"

[[bin]]
name = "secretspec"
path = "src/bin/secretspec.rs"
required-features = ["cli"]

[dependencies]
clap.workspace = true
keyring = { workspace = true, optional = true }
serde.workspace = true
toml.workspace = true
thiserror.workspace = true
directories.workspace = true
colored.workspace = true
rpassword.workspace = true
dotenvy.workspace = true
serde-envfile.workspace = true
inquire.workspace = true
miette.workspace = true
serde_json.workspace = true
tempfile.workspace = true
http.workspace = true
url.workspace = true
whoami = { workspace = true, optional = true }
linkme.workspace = true
secrecy.workspace = true
base64.workspace = true

[features]
default = ["cli", "keyring"]
cli = []
keyring = ["dep:keyring", "dep:whoami"]
