name: "Latest tag"
on:
  push:
    tags:
      - v**
jobs:
  latest-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
    - name: Update 'latest' git tag
      uses: EndBug/latest-tag@8fcae8848c1e23fd8212258f69a9619bc62cad67 # v1.6.3
