name: Publish Crates

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to publish (e.g., 0.1.2 or v0.1.2)"
        required: true
        type: string
  push:
    tags:
      - "*[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish secretspec crate
        run: devenv shell cargo publish -p secretspec
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Publish secretspec-derive crate
        run: devenv shell cargo publish -p secretspec-derive
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
