name: release-pr

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-pr:
    if: github.repository_owner == 'ifiokjr' || github.repository_owner == 'monosecret'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: create release pull request
        uses: monochange/actions@53bd37cbecff25eeefa689bd7ac5fc807dbabac7
        with:
          name: release-pr
          setup-monochange: devenv shell monochange
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: main
