name: release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  monochange:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - uses: dart-lang/setup-dart@v1
      - name: Install monochange
        run: cargo install monochange --locked
      - name: Plan release
        run: monochange plan
      - name: Version packages
        run: monochange version
